#ifndef SKILL_DEFS_H
#define SKILL_DEFS_H

#include <gb/gb.h>

#define SKILL_NONE 0u
#define SKILL_POWER_STRIKE 1u
#define SKILL_HEAL_SIMPLE 2u
#define SKILL_FIRE 3u
#define SKILL_GUARD_BREAK 4u
#define SKILL_SLASH 5u
#define SKILL_DOUBLE_SLASH 6u
#define SKILL_CROSS_SLASH 7u
#define SKILL_FLAME_EDGE 8u
#define SKILL_ICE_EDGE 9u
#define SKILL_DRAGON_REND 10u
#define SKILL_HEAVY_BLOW 11u
#define SKILL_ARMOR_BREAK 12u
#define SKILL_WIND_CUT 13u
#define SKILL_FINAL_BLADE 14u
#define SKILL_STAFF_HIT 15u
#define SKILL_MIND_SPIKE 16u
#define SKILL_HOLY_LIGHT 17u
#define SKILL_MANA_BURST 18u
#define SKILL_SLEEP_MIST 19u
#define SKILL_STAR_PRAYER 20u
#define SKILL_ARROW_SHOT 21u
#define SKILL_DOUBLE_ARROW 22u
#define SKILL_EAGLE_EYE 23u
#define SKILL_PIERCING_ARROW 24u
#define SKILL_THUNDER_ARROW 25u
#define SKILL_RAIN_ARROW 26u
#define SKILL_PUNCH 27u
#define SKILL_IRON_FIST 28u
#define SKILL_COUNTER_FIST 29u
#define SKILL_TIGER_CLAW 30u
#define SKILL_DRAGON_FIST 31u
#define SKILL_SOUL_PALM 32u
#define SKILL_TRAP_SET 33u
#define SKILL_BOMB_THROW 34u
#define SKILL_GEAR_CUTTER 35u
#define SKILL_FLASH_BOMB 36u
#define SKILL_POISON_TRAP 37u
#define SKILL_GRAVITY_NET 38u
#define SKILL_MAGIC_FLAME 39u
#define SKILL_MAGIC_BLIZZARD 40u
#define SKILL_MAGIC_THUNDER 41u
#define SKILL_MAGIC_AQUA 42u
#define SKILL_MAGIC_WIND 43u
#define SKILL_MAGIC_STONE 44u
#define SKILL_MAGIC_SHINE 45u
#define SKILL_MAGIC_DARK 46u
#define SKILL_MAGIC_HEAL_PLUS 47u
#define SKILL_MAGIC_REVIVE 48u
#define SKILL_MAGIC_BARRIER 49u
#define SKILL_MAGIC_METEOR 50u
#define SKILL_MAX 51u

#define PLAYER_SKILL_SLOT_COUNT 50u
#define PLAYER_SKILL_VISIBLE_ROWS 4u

#endif
